<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-05-02T17:34:53 IST" name="Default suite" finished-at="2022-05-02T17:35:22 IST" duration-ms="28581">
    <groups>
    </groups>
    <test started-at="2022-05-02T17:34:53 IST" name="Default test" finished-at="2022-05-02T17:35:22 IST" duration-ms="28581">
      <class name="scripts.Testcase3">
        <test-method is-config="true" signature="openApp()[pri:0, instance:scripts.Testcase3@3315d2d7]" started-at="2022-05-02T17:34:53 IST" name="openApp" finished-at="2022-05-02T17:34:59 IST" duration-ms="6329" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="tc3()[pri:0, instance:scripts.Testcase3@3315d2d7]" started-at="2022-05-02T17:34:59 IST" name="tc3" finished-at="2022-05-02T17:35:20 IST" duration-ms="20512" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [36drr5tytyr6] but found [Learn Core Java for Selenium|Core Java Certification|SkillRary]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [36drr5tytyr6] but found [Learn Core Java for Selenium|Core Java Certification|SkillRary]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at scripts.Testcase3.tc3(Testcase3.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc3 -->
        <test-method is-config="true" signature="closeApp(org.testng.ITestResult)[pri:0, instance:scripts.Testcase3@3315d2d7]" started-at="2022-05-02T17:35:20 IST" name="closeApp" finished-at="2022-05-02T17:35:22 IST" duration-ms="1657" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=tc3 status=FAILURE method=Testcase3.tc3()[pri:0, instance:scripts.Testcase3@3315d2d7] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- scripts.Testcase3 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
